all:
  children:
    my-cloud:
      hosts:
        ubuntu-vps:
          ansible_host: 192.168.0.3
          ansible_user: tochiman
          ansible_password: tochiman1919isnekomatoakayu
          ansible_ssh_private_key_file: ~/.ssh/ubuntu-vps
        school:
          ansible_host: 192.168.0.4
          ansible_user: tochiman
          ansible_password: tochiman1919isnekomatoakayu
          ansible_ssh_private_key_file: ~/.ssh/school
        pve-fujitsu:
          ansible_host: 192.168.0.6
          ansible_user: root
          ansible_password: NTR_tochiman#1919
          ansible_ssh_private_key_file: ~/.ssh/pve-fujitsu
        pve-dell:
          ansible_host: 192.168.0.9
          ansible_user: root
          ansible_password: NTR_tochiman#1919
          ansible_ssh_private_key_file: ~/.ssh/pve-dell
        monitoring:
          ansible_host: 192.168.0.8
          ansible_user: tochiman
          ansible_password: tochiman1919isnekomatoakayu
          ansible_ssh_private_key_file: ~/.ssh/monitoring
    security:
      hosts:
        vyos:
          ansible_host: 192.168.1.254
          ansible_user: vyos
          ansible_password: genbaneko
        directory_server:
          ansible_host: 192.168.1.21
          ansible_user: 389ds
          ansible_password: genbaneko
        file_server1:
          ansible_host: 192.168.1.31
          ansible_user: beegfs
          ansible_password: genbaneko
        file_server2:
          ansible_host: 192.168.1.32
          ansible_user: beegfs
          ansible_password: genbaneko
        file_server3:
          ansible_host: 192.168.1.33
          ansible_user: beegfs
          ansible_password: genbaneko
        dns_ntp:
          ansible_host: 192.168.1.41
          ansible_user: ine
          ansible_password: genbaneko
        proxmox1:
          ansible_host: 192.168.1.51
          ansible_user: pve
          ansible_password: genbaneko
        proxmox2:
          ansible_host: 192.168.1.52
          ansible_user: pve
          ansible_password: genbaneko
        proxmox3:
          ansible_host: 192.168.1.53
          ansible_user: pve
          ansible_password: genbaneko
        proxmox4:
          ansible_host: 192.168.1.54
          ansible_user: pve
          ansible_password: genbaneko
        proxmox5:
          ansible_host: 192.168.1.55
          ansible_user: pve
          ansible_password: genbaneko
        proxmox6:
          ansible_host: 192.168.1.56
          ansible_user: pve
          ansible_password: genbaneko
